---
version: '2'
volumes:
  zkdata:
  brokerdata:
  ccdata:
  secrets:
  cbdata:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.1.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zkdata:/var/lib/zookeeper/data"
      - "secrets:/etc/zookeeper/secrets"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:3.1.1
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - "brokerdata:/var/lib/kafka/data"
      - "secrets:/etc/kafka/secrets"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092'

  schema_registry:
    image: confluentinc/cp-schema-registry:3.1.1
    hostname: schema_registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    volumes:
      - "secrets:/etc/schema-registry/secrets"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  control-center:
    image: confluentinc/cp-enterprise-control-center:3.1.1
    hostname: control-center
    depends_on:
      - zookeeper
      - broker
      - schema_registry
    ports:
      - "9021:9021"
    volumes:
      - "ccdata:/var/lib/confluent-control-center"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      PORT: 9021

